# Formatta il nome del branch come issue-number
branchName: short
# Commento dell'automation per sapere se è andata a buon fine
silent: false
# Elimina branch dopo chiusura issue
autoDeleteBranch: true
