name: Task Progettista
description: Crea una task generica per progettista
title: "Task"
labels: ["task-progettista"]
projects: ["GlitchHub-Team/2"]
type: task
body:
- type: textarea
  id: description
  attributes:
    label: Descrizione della Task

- type: checkboxes
  id: create-branch
  attributes:
    label: Issue Branch
    options:
    - label: "**NON** creare branch per questa issue"
      required: false
